### ISSUE TITLE
Mapping `globalVariables` values to scripts after being initialized 

### ISSUE THREAD

**Issue by CaptainBaldi** [TheWorldMachinima/SScript#11]
I feel like it would be handy if when mapping values to `globalVariables` it would aswell set these values to all currently running scripts, instead of just having them set to `new` SScript's.

As far as I can tell it currently doesn't do this, and I feel like it would be useful.

**Comment by TheWorldMachinima** [comment]
Added.

**Comment by CaptainBaldi** [comment]
Thanks!

**Comment by CaptainBaldi** [comment]
> Added.

For some reason I can't map variables in a script? I can trace `SScript.globalVariables` but trying to use `SScript.globalVariables.set`, `get`, `exists`, `remove`, or `clear` returns a Null Function Pointer error. returning `SScript.globalVariables.self` doesn't return an error but it doesn't seem to be returning anything.
Just a reminder this only happens when I'm accessing it in an SScript instance. Using it in a regular state seems to work fine.

**Comment by TheWorldMachinima** [comment]
> > Added.
> 
> For some reason I can't map variables in a script? I can trace `SScript.globalVariables` but trying to use `SScript.globalVariables.set`, `get`, `exists`, `remove`, or `clear` returns a Null Function Pointer error. returning `SScript.globalVariables.self` doesn't return an error but it doesn't seem to be returning anything. Just a reminder this only happens when I'm accessing it in an SScript instance. Using it in a regular state seems to work fine.

Currently `globalVariables` are an abstract and they cannot be accessed in SScript instances since they don't exist in runtime.
