### ISSUE TITLE
Macro Issue

### ISSUE THREAD

**Issue by Skullbite** [TheWorldMachinima/SScript#12]
- Error: `(unknown) : Method checkOpenFL not found on class macro.Macro`
- SScript Version: 5.1.0
- OpenFL Version: 9.2.2
- Target OS: macos

This error springs simply from sscript being in my package list, not even being used. My best guess would be to check any use of `macro.Macro`.

**Comment by TheWorldMachinima** [comment]
This is not a Macro issue, this bug happens on Visual Studio Code when a newer version of SScript is installed. 
Reinstall your Haxe extension of VSC or reinstall VSC itself.

**Comment by Skullbite** [comment]
While this error affects the haxe interpreter extension, it also occurs when attempting to compile with lime, regardless of the status of VSC or the haxe extension.

<img width="509" alt="image" src="https://github.com/TheWorldMachinima/SScript/assets/20869262/25096db7-79b3-4f23-99f3-1a52f188d978">

**Comment by TheWorldMachinima** [comment]
> While this error affects the haxe interpreter extension, it also occurs when attempting to compile with lime, regardless of the status of VSC or the haxe extension.
> 
> <img alt="image" width="509" src="https://user-images.githubusercontent.com/20869262/267197789-25096db7-79b3-4f23-99f3-1a52f188d978.png">

I never had this issue while compiling, probably two SScript versions are installed on your Mac, remove SScript and reinstall it again.

**Comment by Skullbite** [comment]
Oddly removing my entire SScript folder from haxe/lib fixed the issue.
