### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by afeefflox** [TheWorldMachinima/SScript#4]
so uh when I'm compile it show error this![e](https://user-images.githubusercontent.com/83808420/222536497-aef00564-3a40-4d4e-8072-4d405419897a.PNG)

**Comment by TheWorldMachinima** [comment]
Do not use 1.9.9, it will not work.
Update to the latest one.

`haxelib remove SScript`
`haxelib git SScript https://github.com/TheWorldMachinima/SScript.git`
