### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Hiho2950** [TheWorldMachinima/SScript#8]
hi i use package , it s so cool;
my issue is with class when i make for example class ParentClass {}
the error is unexpected ParentClass
so pls fix it

**Comment by TheWorldMachinima** [comment]
> hi i use package , it s so cool; my issue is with class when i make for example class ParentClass {} the error is unexpected ParentClass so pls fix it

You need to enable class support before using it.
`SScript.defaultClassSupport = true;`
